<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta type="viewport" content="width=device-width,initial-scale=1">
	<title>对于promise的理解</title>
</head>
<body>
<h1>promise的理解</h1>
<!-- 第一种常用方式 -->
<!-- <script type="text/javascript">
	(function es6(){
		let n = 0;
		function proFn1(){
			return new Promise((resolve,reject)=>{
				console.log("第一个");
				resolve(n);
				n++;
			});
		}
		function proFn2(){
			return new Promise((resolve,reject)=>{
				console.log("第二个");
				/*resolve(2);*/
				reject("第二个有问题"+n);
				n++;
			});
		}
		function proFn3(){
			return new Promise((resolve,reject)=>{
				console.log("第三个");
				resolve(n);
				n++;
			});
		}
		function proFn4(){
			return new Promise((resolve,reject)=>{
				console.log("第四个");
				resolve(n);
				n++;
				
			});
		}
		proFn1()
		.then(proFn2)
		.then(proFn3)
		.then(data=>{console.log(data);})
		.catch(err=>{
			console.log(err);
		});
	})();
	var p1 = new Promise(function (resolve, reject) {
setTimeout(() => resolve(new Error('fail')), 3000)
})
var p2 = new Promise(function (resolve, reject) {
setTimeout(() => resolve(p1), 1000)
})
p2
.then(result => console.log(result),(err)=>console.log(err))
/*.then(resutl=>console.log(resutl),err=>console.log(err));*/
.catch(error => console.log(error))//Promise.prototype.catch方法是.then(null, rejection)的别名，用于指定发生错误时的回调函数，p1抛出错误也算是报错了catch就会捕捉到，只要是代码中运行出现错误，catch都能捕捉到，所以在写的时候，最好不要讲then的第二个参数加上，而是用catch来捕捉错误，执行中错误会一直冒泡到catch捕捉到,但是也只能捕捉在这之前的错误，之后的错误捕捉不到


/*实际例子*/
var someAsyncThing = function() {
return new Promise(function(resolve, reject) {
//  下面一行会报错，因为 x 没有声明
resolve(x + 2);
});
};
someAsyncThing().then(function() {
console.log('everything is great');
});
/*上面代码中，someAsyncThing函数产生的 Promise 对象会报错，但是由于没有指定catch方法，这个错误不会被捕获，也不会传递到外层代码，导致运
行后没有任何输出。                          注意， Chrome 浏览器不遵守这条规定，它会抛出错误 “ReferenceError: x is not defined” */
</script> -->


<script type="text/javascript">
/*****promise执行的时间在这一次循环的结束之前********* 定时器是在下次循环的开始之前执行********************************其他代码是立即执行*/
	setTimeout(()=>{console.log(1);},0);
	var aa=new Promise((resolve,reject)=>{
		resolve();
	});
	aa.then(function(){
		console.log(2);
	});	
	console.log(3);
</script>
</body>
</html>